from flask import Flask

app = Flask(__name__)


@app.route('/')
def hello_world():  # put application's code here
    # deze code is gewoon voor de test, gaat later sws weg
    html_content = """
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>CLASH OF PPDB'S</title>
                <style>
                    body {
                        background-color: #f8f9fa;
                        font-family: Arial, sans-serif;
                        margin: 0;
                        padding: 0;
                        display: flex;
                        justify-content: center;
                        align-items: center;
                        height: 100vh;
                    }
                    .container {
                        text-align: center;
                        padding: 20px;
                        border-radius: 10px;
                        background-color: #fff;
                        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
                    }
                    h1 {
                        color: #007bff;
                        margin-bottom: 20px;
                    }
                    p {
                        color: #333;
                    }
                </style>
            </head>
            <body>
                <div class="container">
                    <h1>CLASH OF PPDB'S</h1>
                    <p>This is a simple page designed page generated by Flask by displaying temporary HTML code.</p>
                </div>
            </body>
            </html>
            """
    return html_content


if __name__ == '__main__':
    app.run()
