/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Karumaki (https://sketchfab.com/Karumaki)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rauma-town-hall-e2c47838ebde464bbcea521c0ff5ce9e
Title: Rauma Town Hall
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import chancery from '../../../assets/chancery.glb'

/**
 * React component for rendering a 3D model of Rauma Town Hall Chancery.
 * @param {object} props - Props passed to the component.
 * @returns {JSX.Element} JSX representation of the Chancery.
 */
function Chancery({props}) {
  const { nodes, materials } = useGLTF(chancery)
  return (
    <group {...props} dispose={null} scale={0.002+props} position={[4.35,0,3]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Main_skp_front_default_0.geometry}
        material={materials.skp_front_default}
        position={[-664.086, 0, -528.21]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload(chancery)

export default Chancery;