/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: bobrik00 (https://sketchfab.com/bobrik00)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/windmill-2c54d1c79d27428aaea4d0909cae0635
Title: Windmill
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import farm from '../../../assets/farm.glb'
import Quarry from "./Quarry.jsx";

/**
 * React component for rendering a 3D model of a windmill on a farm.
 * @param {object} props - Props passed to the component.
 * @returns {JSX.Element} JSX representation of the windmill farm.
 */
function Farm({props}) {
  const { nodes, materials } = useGLTF(farm)
  return (
    <group {...props} dispose={null} scale={0.8+props} position={[1, 0.2, 1]}>
        <group scale={2}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.002}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.lod_0_windmill_0.geometry}
            material={materials.windmill}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
        </group>
    </group>
  )
}

useGLTF.preload(farm)

export default Farm;