/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: whitegoldgd (https://sketchfab.com/whitegoldgd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/decoration-7a2b0b35fa65403ab61753afbab23d97
Title: Decoration
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gazebo from '../../../assets/gazebo.glb'

export default function Gazebo(props) {
  const { nodes, materials } = useGLTF(gazebo)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bench_low_Bench_M_0.geometry}
        material={materials.Bench_M}
        position={[-1079.35, 155.056, 893.322]}
        rotation={[-Math.PI / 2, 0, 0.378]}
        scale={108.912}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.alcove_low_Alcove_M_0.geometry}
        material={materials.Alcove_M}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload(gazebo)
