/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: whitegoldgd (https://sketchfab.com/whitegoldgd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/decoration-7a2b0b35fa65403ab61753afbab23d97
Title: Decoration
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gazebo from '../../../assets/gazebo.glb'

/**
 * Represents a Gazebo component.
 * @component
 * @param {object} props - Props for the Gazebo component.
 * @returns {JSX.Element} A Gazebo component.
 */

export default function Gazebo(props) {
  const { nodes, materials } = useGLTF(gazebo)
  return (
    <group {...props} dispose={null} scale={0.002} position={[1,0.2,0.5]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.alcove_low_Alcove_M_0.geometry}
        material={materials.Alcove_M}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload(gazebo)
