/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ville Seppänen (https://sketchfab.com/accuman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/snake-statue-794b77a3e4654a669cf259d20dc89ec7
Title: Snake Statue
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import snakeStatue from '../../../assets/snakeStatue.glb'
export default function SnakeStatue(props) {
  const { nodes, materials } = useGLTF(snakeStatue)
  return (
    <group {...props} dispose={null} scale={0.5} position={[1.5,0,1.35]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stone_0.geometry}
          material={materials.stones}
          position={[0, 0, 4.065]}
          rotation={[Math.PI / 2, -1.407, 0]}
          scale={0.034}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.snakelp_0.geometry}
          material={materials.snake}
          position={[0, 0, 7.062]}
          rotation={[Math.PI / 2, 0.183, 0]}
          scale={0.038}
        />
      </group>
    </group>
  )
}

useGLTF.preload(snakeStatue)
