/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ashkan.Khelghati (https://sketchfab.com/Ashkan.Khelghati)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/statue-08aa8c9b10fb4ba189a030582b942b13
Title: Statue
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import waterStatue from '../../../assets/waterStatue.glb'

export default function WaterStatue(props) {
  const { nodes, materials } = useGLTF(waterStatue)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.556}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.M_0010_Snow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Stone_Marble_VermontDanby}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Stone_Speckled_Multi}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.Stone__Granite_Speckled}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.Tile_Ceramic_Tan}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.Translucent_Glass_Aqua}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.Water_Pool}
        />
      </group>
    </group>
  )
}

useGLTF.preload(waterStatue)
