/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: olmopotums (https://sketchfab.com/olmopotums)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-noble-craftsman-0e8ff87ffaa24731b2474badebca870d
Title: The Noble Craftsman
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import craftsMan from '../assets/the_noble_craftsman.glb'

function CraftsMan(props) {
  const { nodes, materials } = useGLTF(craftsMan);
  return (
    <group {...props} dispose={null}>
        <group scale={0.08}>
            <group
                position={[-11.552, 43.571, -3.74]}
                rotation={[-Math.PI / 2, 0, 0]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes["m_ShoulderPads_02_-_Default_0"].geometry}
                    material={materials["02_-_Default"]}
                    position={[11.552, -3.74, -43.571]}
                />
            </group>
            <group position={[0, 20.466, -2.239]} rotation={[1.567, 1.571, 0]}>
                <group position={[1.014, -0.078, 0]} rotation={[0, 0, 0.122]}>
                    <group position={[12.339, 0, 0]} rotation={[0, 0, -0.283]}>
                        <group position={[10.512, 0, 0]} rotation={[0, 0, 0.164]}>
                            <group
                                position={[-4.254, 2.121, 9.29]}
                                rotation={[-1.654, -1.461, -2.304]}
                            >
                                <group
                                    position={[5.245, 0, 0]}
                                    rotation={[0.651, -0.649, 0.946]}
                                >
                                    <group
                                        position={[9.896, 0, 0]}
                                        rotation={[0.235, -0.249, 1.045]}
                                    >
                                        <group
                                            position={[11.673, 0, 0]}
                                            rotation={[-1.607, -0.128, -0.161]}
                                        >
                                            <group
                                                position={[9.31, -33.634, 5.563]}
                                                rotation={[-1.726, 0.056, 1.646]}
                                            >
                                                <mesh
                                                    castShadow
                                                    receiveShadow
                                                    geometry={nodes["m_Hammer_02_-_Default_0"].geometry}
                                                    material={materials["02_-_Default"]}
                                                    position={[-39.226, 48.736, 29.391]}
                                                />
                                            </group>
                                        </group>
                                    </group>
                                </group>
                            </group>
                            <group
                                position={[-4.254, 2.121, -9.29]}
                                rotation={[2.63, 1.312, -3.095]}
                            >
                                <group
                                    position={[5.245, 0, 0]}
                                    rotation={[-0.416, 0.552, 0.57]}
                                >
                                    <group
                                        position={[9.896, 0, 0]}
                                        rotation={[-0.315, -0.151, 0.813]}
                                    >
                                        <group
                                            position={[11.673, 0, 0]}
                                            rotation={[1.012, -0.222, -0.274]}
                                        >
                                            <group
                                                position={[1.42, -0.633, -1.397]}
                                                rotation={[1.673, 0.774, -1.625]}
                                            >
                                                <mesh
                                                    castShadow
                                                    receiveShadow
                                                    geometry={nodes["m_HotIron_02_-_Default_0"].geometry}
                                                    material={materials["02_-_Default"]}
                                                    position={[16.696, 47.74, -0.555]}
                                                />
                                            </group>
                                        </group>
                                    </group>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
            <group
                position={[-11.511, 44.771, -5.308]}
                rotation={[-1.925, -0.251, 0.17]}
                scale={[1, 1.03, 1]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes["Object008_02_-_Default_0"].geometry}
                    material={materials["02_-_Default"]}
                    position={[11.552, -3.74, -43.571]}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["LO_Anvil_09_-_Default_0"].geometry}
                material={materials["09_-_Default"]}
                position={[0, 0, 23.367]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.937}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["m_Mesh_02_-_Default_0"].geometry}
                material={materials["02_-_Default"]}
                rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Plane001_03_-_Default_0"].geometry}
                material={materials["03_-_Default"]}
                position={[1.668, 0, 10.834]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[1.26, 1.26, 0.886]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Plane004_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
                position={[9.94, 23.342, 23.127]}
                rotation={[0, 0, -0.087]}
                scale={0.105}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Plane005_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
                position={[-9.784, 24.797, 23.127]}
                rotation={[0, 0, 2.094]}
                scale={0.117}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Plane006_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
                position={[1.67, 11.562, 36.132]}
                rotation={[-2.618, 1.396, -0.087]}
                scale={0.119}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Plane007_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
                position={[-5.533, 20.37, 30.496]}
                rotation={[0, Math.PI / 3, 2.182]}
                scale={0.114}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Plane008_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
                position={[3.002, 23.325, 17.501]}
                rotation={[0, Math.PI / 3, -0.087]}
                scale={0.1}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Plane009_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
                position={[-2.617, 22.141, 21.804]}
                rotation={[-Math.PI, 0.611, 3.054]}
                scale={0.1}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Plane010_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
                position={[6.103, 16.987, 15.38]}
                rotation={[-3.01, -0.845, 0.528]}
                scale={0.119}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Plane011_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
                position={[6.415, 20.37, 24.52]}
                rotation={[Math.PI, -0.175, -0.96]}
                scale={0.114}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Plane012_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
                position={[3.502, 24.797, 32.513]}
                rotation={[Math.PI, 0.873, -Math.PI / 3]}
                scale={0.117}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Plane013_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
                position={[-0.888, 21.875, 27.667]}
                rotation={[0, -1.484, -0.087]}
                scale={0.1}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Plane014_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
                position={[-16.835, 28.851, 26.335]}
                rotation={[-Math.PI, -0.175, 3.054]}
                scale={0.1}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Plane015_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
                position={[-7.469, 27.92, 19.438]}
                rotation={[-Math.PI, 0.873, 3.054]}
                scale={0.105}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Plane016_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
                position={[0.182, 21.875, 22.585]}
                rotation={[-Math.PI, 0.175, 3.054]}
                scale={0.1}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Plane017_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
                position={[1.478, 20.275, 26.415]}
                rotation={[0, 1.484, 2.182]}
                scale={0.114}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Plane018_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
                position={[-5.98, 24.797, 24.369]}
                rotation={[0, 0.436, 2.094]}
                scale={0.117}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Plane019_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
                position={[4.792, 22.141, 22.41]}
                rotation={[0, 0.698, -0.087]}
                scale={0.1}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Plane020_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
                position={[8.65, 23.325, 27.77]}
                rotation={[0, -Math.PI / 4, -0.087]}
                scale={0.1}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Plane021_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
                position={[0.181, 27.999, 22.998]}
                rotation={[0.135, -0.572, 0.783]}
                scale={0.1}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Plane022_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
                position={[21.039, 23.325, 27.77]}
                rotation={[-0.754, -0.244, -1.406]}
                scale={0.1}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Plane023_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
                position={[-2.99, 34.51, 22.998]}
                rotation={[0.135, -0.572, 0.783]}
                scale={0.1}
            />
        </group>
    </group>
  );
}

useGLTF.preload("/the_noble_craftsman.glb");

export default CraftsMan;