/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: mhart (https://sketchfab.com/mhart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rocky-ground-with-moss-2c0386dd36124ad78f37dbf6432eac21
Title: Rocky Ground with Moss
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import ground from '../assets/ground.glb'

export default function Ground(props) {
  const { nodes, materials } = useGLTF(ground)
  return (
    <group {...props} dispose={null} scale={5} position={[0,5,0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ground_0.geometry}
          material={materials.ground}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ground_0_1.geometry}
          material={materials.ground}
        />
      </group>
    </group>
  )
}

useGLTF.preload(ground)
