/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: tiunov.se (https://sketchfab.com/tiunov.se)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/checkpoint-cdeb04f317854d54b23574caeb7845d5
Title: Checkpoint
*/

import React, {useEffect, useRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import capital from '../assets/capital.glb'

export default function Capital(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(capital)
  const { actions, names} = useAnimations(animations, group)

  useEffect(() =>
  {
    actions[names[0]].reset().fadeIn(10).play()
  }, [])
  return (
    <group ref={group} {...props} dispose={null} scale={[17,20,17]} position={[0,-2.2,0]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="trigfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Cylinder001"
                  position={[0.196, 0, 0.196]}
                  rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Cylinder001_Material_#25_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Cylinder001_Material_#25_0'].geometry}
                    material={materials.Material_25}
                  />
                </group>
                <group
                  name="Object001"
                  position={[0.196, 0, 0.196]}
                  rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Object001_Material_#25_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Object001_Material_#25_0'].geometry}
                    material={materials.Material_25}
                  />
                </group>
                <group
                  name="Object002"
                  position={[0.196, 0, 0.196]}
                  rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Object002_Material_#25_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Object002_Material_#25_0'].geometry}
                    material={materials.Material_25}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(capital)
