/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Bastien Genbrugge (https://sketchfab.com/bastienBGR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ship-in-clouds-c475323dc7f24e26ba2009c08c8e1941
Title: Ship in Clouds
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import environment from '../assets/environment.glb'

export default function Environment(props) {
  const { nodes, materials } = useGLTF(environment)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.09} position={[0,0,100]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sky_Mat_0.geometry}
            material={materials.material}
            position={[51.637, 0, -817.579]}
            rotation={[0, -Math.PI / 2, 0]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(environment)
