/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Cxrly97 (https://sketchfab.com/Cxrly97)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/final-landscape-704eed05e4c94cc7b1ed1008277a5a2a
Title: Final Landscape
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import landscape from '../assets/landscape.glb'

export default function Landscape(props) {
  const { nodes, materials } = useGLTF(landscape)
  return (
    <group {...props} dispose={null} scale={0.1} position={[35,4.55,50]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.landscape_lambert5_0.geometry}
        material={materials.lambert5}
        position={[5.476, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_045_lambert19_0.geometry}
        material={materials.lambert19}
        position={[324.764, -7.894, 769.706]}
        scale={11.66}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_046_lambert19_0.geometry}
        material={materials.lambert19}
        position={[318.736, 8.659, 702.419]}
        scale={4.16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_047_lambert31_0.geometry}
        material={materials.lambert31}
        position={[1257.85, -94.238, 114.071]}
        scale={49.829}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_048_lambert31_0.geometry}
        material={materials.lambert31}
        position={[745.069, -104.273, 524.737]}
        scale={53.659}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_049_lambert31_0.geometry}
        material={materials.lambert31}
        position={[142.863, -146.625, -1046.134]}
        scale={61.83}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_051_lambert31_0.geometry}
        material={materials.lambert31}
        position={[832.446, -153.508, -534.758]}
        scale={52.429}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_052_lambert31_0.geometry}
        material={materials.lambert31}
        position={[1824.86, -14.242, -9.384]}
        scale={80.262}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_053_lambert31_0.geometry}
        material={materials.lambert31}
        position={[1060.601, -91.352, 212.718]}
        scale={73.661}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_054_lambert31_0.geometry}
        material={materials.lambert31}
        position={[1395.656, 55.717, 136.368]}
        scale={60.157}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_055_lambert31_0.geometry}
        material={materials.lambert31}
        position={[805.577, -45.283, -466.616]}
        scale={22.12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_056_lambert31_0.geometry}
        material={materials.lambert31}
        position={[1620.493, -216.94, 1290.147]}
        rotation={[0, -0.649, 0]}
        scale={118.73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_057_lambert31_0.geometry}
        material={materials.lambert31}
        position={[11.721, -68.58, -1044.69]}
        scale={38.972}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_058_lambert31_0.geometry}
        material={materials.lambert31}
        position={[76.555, 37.683, -791.524]}
        rotation={[0.474, -0.625, 0.72]}
        scale={36.614}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_059_lambert31_0.geometry}
        material={materials.lambert31}
        position={[909.827, 1.019, 155.132]}
        scale={19.237}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass_05_lambert18_0.geometry}
        material={materials.lambert18}
        position={[216.667, -103.735, -733.456]}
        scale={28.455}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_060_lambert19_0.geometry}
        material={materials.lambert19}
        position={[119.066, 85.733, 771.617]}
        rotation={[3.093, 0.589, -2.75]}
        scale={23.409}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_083_lambert19_0.geometry}
        material={materials.lambert19}
        position={[1035.808, 5.312, 1268.326]}
        rotation={[0, -0.809, 0]}
        scale={43.165}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_084_lambert19_0.geometry}
        material={materials.lambert19}
        position={[844.326, 68.934, 1035.95]}
        rotation={[-0.431, 0, 0]}
        scale={26.493}
      />
    </group>
  )
}

useGLTF.preload(landscape)
