/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: yonimantz (https://sketchfab.com/yonimantz09)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-water-treasure-44fd8735cc6e4a6f8806f7a6a4130ed7
Title: Old Water Treasure
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import map from '../assets/map.glb';

export default function Paper(props) {
  const { nodes, materials } = useGLTF(map)
  return (
    <group {...props} dispose={null} scale={0.3} position={[30,3,20]}>
      <group position={[-252.53, 10.809, -99.706]} rotation={[-1.592, -0.032, 0.001]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003_gold001_0.geometry}
          material={materials['gold.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003_glass002_0.geometry}
          material={materials['glass.002']}
        />
      </group>
      <group
        position={[-250.078, 26.584, -201.154]}
        rotation={[-1.585, 0.003, -0.598]}
        scale={28.254}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004_compassbasic001_0.geometry}
          material={materials['compassbasic.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004_click001_0.geometry}
          material={materials['click.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004_tiny_001_0.geometry}
          material={materials['tiny_.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004_compass001_0.geometry}
          material={materials['compass.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004_compass_paper001_0.geometry}
          material={materials['compass_paper.001']}
        />
      </group>
      <group
        position={[111.982, -0.576, -118.47]}
        rotation={[-Math.PI / 2, 0, -1.062]}
        scale={47.556}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005_gold_base001_0.geometry}
          material={materials['gold_base.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005_glass003_0.geometry}
          material={materials['glass.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005_fire_base001_0.geometry}
          material={materials['fire_base.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005_gold_3001_0.geometry}
          material={materials['gold_3.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005_gold_2001_0.geometry}
          material={materials['gold_2.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005_gold_4001_0.geometry}
          material={materials['gold_4.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005_fire001_0.geometry}
          material={materials['fire.001']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_map_0.geometry}
        material={materials.material}
        position={[-190.228, -0.249, -40.613]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube000__0.geometry}
        material={materials['Cube.000__0']}
        position={[-144.383, -2.572, -47.085]}
        rotation={[-Math.PI / 2, 0, -0.938]}
        scale={[133.954, 100, 100]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle006_glass_2001_0.geometry}
        material={materials['glass_2.001']}
        position={[-263.783, 15.018, -186.741]}
        rotation={[-1.585, 0.003, -0.598]}
        scale={28.827}
      />
    </group>
  )
}

useGLTF.preload(map)
