/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: hamidkhan224 (https://sketchfab.com/hamidkhan224)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/castle-80793eb36b1f4179879f8df143bb3606
Title: Castle
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import settlementType3 from '../assets/settlementType3.glb'

export default function Settlement3(props) {
  const { nodes, materials } = useGLTF(settlementType3)
  return (
    <group {...props} dispose={null} scale={4} position={[0,0.5,-1]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.material}
        position={[0.01, -0.108, 0.242]}
        scale={0.057}
      />
    </group>
  )
}

useGLTF.preload(settlementType3)
