/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Young_Wizard (https://sketchfab.com/illya2878)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medieval-house-4ec56df1c24d422ea85d1cfbf21bbe8c
Title: Medieval house
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import barracks from '../assets/barracks.glb'

export default function Barracks(props) {
  const { nodes, materials } = useGLTF(barracks)
  return (
    <group {...props} dispose={null} scale={0.3}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload(barracks)
