/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Daniel (https://sketchfab.com/DanielAndersson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medieval-blacksmith-2e4f2725963644c685419dea1e4430df
Title: Medieval Blacksmith
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import blackSmith from '../assets/blackSmith.glb'

/**
 * React component for rendering a 3D model of a Medieval Blacksmith.
 * @param {object} props - Props passed to the component.
 * @returns {JSX.Element} JSX representation of the blacksmith.
 */
export default function BlackSmith(props) {
  const { nodes, materials } = useGLTF(blackSmith)
  return (
    <group {...props} dispose={null} scale={0.9} position={[0,0.55,0]}>
      <group scale={0.5}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-3.754, 0.698, -0.612]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Barrel1_1.geometry}
            material={materials.Wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Barrel1_2.geometry}
            material={materials.RustedMetal}
          />
        </group>
        <group position={[-4.834, 0.67, -0.011]} rotation={[1.34, 0.511, -1.456]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tools_1.geometry}
            material={materials.WroughtIron}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tools_2.geometry}
            material={materials.Wood}
          />
        </group>
        <group position={[-5.145, 0.754, -0.413]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.WorkBench_1.geometry}
            material={materials.Wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.WorkBench_2.geometry}
            material={materials.LogEdgeWeathered}
          />
        </group>
        <group
          position={[-1.361, 5.496, -0.854]}
          rotation={[-2.716, 0, 0]}
          scale={[1, 0.698, 0.698]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PileofChoppedWood_1.geometry}
            material={materials.Bark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PileofChoppedWood_2.geometry}
            material={materials.LogEdge}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PileofChoppedWood_3.geometry}
            material={materials.ChoppedWood}
          />
        </group>
        <group position={[-0.807, 7.173, -0.842]} rotation={[0, Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ShortLog_1.geometry}
            material={materials.Bark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ShortLog_2.geometry}
            material={materials.LogEdge}
          />
        </group>
        <group position={[0.238, 5.879, -1.102]} rotation={[-0.953, -0.008, -1.565]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PileOfLogs_1.geometry}
            material={materials.Bark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PileOfLogs_2.geometry}
            material={materials.LogEdge}
          />
        </group>
        <group position={[-0.791, 7.185, -0.291]} rotation={[2.551, -0.4, 2.098]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.WoodCutters_Axe_1.geometry}
            material={materials.Iron}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.WoodCutters_Axe_2.geometry}
            material={materials.Wood}
          />
        </group>
        <group position={[-6.579, 0.489, -0.34]} rotation={[0, 0, 1.805]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Grindstone_1.geometry}
            material={materials.WroughtIron}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Grindstone_2.geometry}
            material={materials.Wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Grindstone_3.geometry}
            material={materials.LogEdgeWeathered}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Grindstone_4.geometry}
            material={materials.Sandstone}
          />
        </group>
        <group position={[-2.746, -0.086, -0.908]} rotation={[0, 0, -1.576]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.AnvilStand_1.geometry}
            material={materials.WroughtIron}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.AnvilStand_2.geometry}
            material={materials.OakBark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.AnvilStand_3.geometry}
            material={materials.LogEdgeWeathered}
          />
        </group>
        <group position={[-3.5, -1.285, -0.553]} rotation={[0, 0, 0.067]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Forge_1.geometry}
            material={materials.GreyBrick}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Forge_2.geometry}
            material={materials.Coal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Forge_3.geometry}
            material={materials.WroughtIron}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Forge_4.geometry}
            material={materials.Stone}
          />
        </group>
        <group position={[-4.993, -1.39, -0.72]} rotation={[0, 0, 0.067]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bellow_1.geometry}
            material={materials.WroughtIron}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bellow_2.geometry}
            material={materials.Wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bellow_3.geometry}
            material={materials.LogEdgeWeathered}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bellow_4.geometry}
            material={materials.BrownLeather}
          />
        </group>
        <group position={[-0.234, -1.707, 0.778]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DoorFrontFrame_1.geometry}
            material={materials.Wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DoorFrontFrame_2.geometry}
            material={materials.LogEdgeWeathered}
          />
        </group>
        <group position={[-6.336, 2.953, 0.129]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DoorSideFrame_1.geometry}
            material={materials.Wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DoorSideFrame_2.geometry}
            material={materials.LogEdgeWeathered}
          />
        </group>
        <group position={[-3.997, 4.662, 0.284]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.WoodenBeams_1.geometry}
            material={materials.Wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.WoodenBeams_2.geometry}
            material={materials.LogEdgeWeathered}
          />
        </group>
        <group position={[0.064, 3.09, 5.817]} rotation={[0, 0, Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.WindowFrames_1.geometry}
            material={materials.LogEdgeWeathered}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.WindowFrames_2.geometry}
            material={materials.Wood}
          />
        </group>
        <group position={[0.785, 1.166, 7.141]} rotation={[0, 0, Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.RoofFrame_1.geometry}
            material={materials.Wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.RoofFrame_2.geometry}
            material={materials.LogEdgeWeathered}
          />
        </group>
        <group position={[-3.077, 0.683, -0.612]} rotation={[Math.PI / 2, -0.81, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Barrel2_1.geometry}
            material={materials.Wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Barrel2_2.geometry}
            material={materials.RustedMetal}
          />
        </group>
        <group
          position={[-1.775, -2.229, 1.841]}
          rotation={[-0.583, 0, -Math.PI]}
          scale={[0.376, 0.476, 0.476]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.WoodenBeams002_1.geometry}
            material={materials.Wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.WoodenBeams002_2.geometry}
            material={materials.LogEdgeWeathered}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.WoodenBeams002_3.geometry}
            material={materials.RustedMetal}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ChimneyPipes_1.geometry}
          material={materials.RustedMetal}
          position={[-1.733, 4.27, 7.114]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={0.585}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chimney_1.geometry}
          material={materials.Brick}
          position={[-1.733, 4.27, 5.632]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={0.585}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AnvilBolts_1.geometry}
          material={materials.WroughtIron}
          position={[-2.741, -0.085, -0.43]}
          rotation={[0, 0, -1.576]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Anvil_1.geometry}
          material={materials.WroughtIron}
          position={[-2.741, -0.083, -0.43]}
          rotation={[0, 0, -1.576]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Level1_1.geometry}
          material={materials.GreyBrick2}
          position={[-5.077, 5.283, 0.037]}
          rotation={[0, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Level2_1.geometry}
          material={materials.Plaster}
          position={[1.766, 1.392, 3.421]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DoorFront_1.geometry}
          material={materials.DoorType1_2}
          position={[-0.234, -1.707, 0.778]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Steps_1.geometry}
          material={materials.GreyStone2}
          position={[-0.225, -4.305, -1.511]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DoorSide_1.geometry}
          material={materials.DoorType1_2}
          position={[-6.336, 2.953, 0.129]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DoorSideHandle_1.geometry}
          material={materials.RustedMetal}
          position={[-6.414, 2.873, 0.192]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DoorSideSteps_1.geometry}
          material={materials.Stone}
          position={[-6.339, 2.953, 0.129]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DoorFrontHandle_1.geometry}
          material={materials.RustedMetal}
          position={[-0.088, -1.797, 0.919]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodenBeamsExtraFront_1.geometry}
          material={materials.Wood}
          position={[-7.007, -2.288, 1.043]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Window1Level1_1.geometry}
          material={materials.WindowBlue1}
          position={[1.811, -0.081, 0.975]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Window2Level1_1.geometry}
          material={materials.WindowBlue1}
          position={[1.811, 1.9, 0.975]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Window8Level2_1.geometry}
          material={materials.WindowBlue1}
          position={[-2.365, -0.526, 3.946]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Window7Level2_1.geometry}
          material={materials.WindowBlue1}
          position={[-2.365, 1.971, 3.946]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Window6Level2_1.geometry}
          material={materials.WindowBlue1}
          position={[-0.2, 5.475, 4.094]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Window3Level2_1.geometry}
          material={materials.WindowBlue2}
          position={[0.439, -2.987, 4.208]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Window1Level2_1.geometry}
          material={materials.WindowBlue2}
          position={[-0.904, -2.982, 4.208]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Window2Level2_1.geometry}
          material={materials.WindowBlue2}
          position={[-0.222, -3.291, 4.208]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Window4Level2_1.geometry}
          material={materials.WindowBlue1}
          position={[1.857, -0.553, 3.946]}
          rotation={[0, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Window5Level2_1.geometry}
          material={materials.WindowBlue1}
          position={[1.857, 3.282, 3.946]}
          rotation={[0, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WindowsHandles_1.geometry}
          material={materials.RustedMetal}
          position={[-4.761, 4.822, 0.774]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Window3Level1_1.geometry}
          material={materials.WindowBlue1}
          position={[-4.753, 4.728, 0.792]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Window1Level3_1.geometry}
          material={materials.WindowBlue2}
          position={[1.54, 1.172, 6.301]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Level3_1.geometry}
          material={materials.Plaster}
          position={[0.536, 1.164, 6.588]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodenBeamsExtraBack_1.geometry}
          material={materials.Wood}
          position={[-2.1, 5.843, 0.573]}
          rotation={[-0.553, 0, Math.PI / 2]}
          scale={[1, 0.872, 0.872]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.IronHotEdge1_1.geometry}
          material={materials.HotIron}
          position={[-3.604, -0.706, -0.377]}
          rotation={[0.782, 0.024, 1.594]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.IronHotEdge2_1.geometry}
          material={materials.HotIron}
          position={[-3.478, -0.773, -0.431]}
          rotation={[0.71, 0.042, 1.606]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ToolHangers_1.geometry}
          material={materials.WroughtIron}
          position={[-5.718, 0.372, -0.109]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roof_1.geometry}
          material={materials.RoofTiles}
          position={[-1.624, 1.702, 5.532]}
          rotation={[0, 0, -Math.PI / 2]}
        />
      </group>
      </group>
    </group>
  )
}

useGLTF.preload(blackSmith)
