/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Avmifi (https://sketchfab.com/Avmifi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/farm-low-poly-116065ff36c64fe9b8e8edcf6c382a50
Title: Farm (low poly)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import farm from '../assets/farm.glb'

export default function Farm(props) {
  const { nodes, materials } = useGLTF(farm)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial.geometry}
            material={materials.lambert3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.lambert4}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(farm)
