/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Den (https://sketchfab.com/dfomenco)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medieval-tower-6c821f2aae3b4e8db5d94c6f48fb568b
Title: Medieval Tower
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import grainSilo from '../assets/grainSilo.glb'

export default function GrainSilo(props)
{
  const { nodes, materials } = useGLTF(grainSilo)
  return (
    <group {...props} dispose={null}>
      <group position={[0, 3.8, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.35}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tower_Brick_MT_0.geometry}
          material={materials.Brick_MT}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tower_Plaster_MT_0.geometry}
          material={materials.Plaster_MT}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tower_Roof_MT_0.geometry}
          material={materials.Roof_MT}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tower_Details_MT_0.geometry}
          material={materials.Details_MT}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tower_Glass_MT_0.geometry}
          material={materials.Glass_MT}
        />
      </group>
    </group>
  )
}

useGLTF.preload(grainSilo)
