/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Aleksandr Boitsun (https://sketchfab.com/Aleks41)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medieval-tower-45a6c29ac5b44c608fea237840e31cca
Title: Medieval Tower
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import lookoutTower from '../assets/lookoutTower.glb'

export default function LookoutTower(props) {
  const { nodes, materials } = useGLTF(lookoutTower)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.8} position={[0,0.1,0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.TowerBase_low_Tower_0.geometry}
            material={materials.Tower}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.WoodCircle_low_Tower_0.geometry}
            material={materials.Tower}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wood_low_Tower_0.geometry}
            material={materials.Tower}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Door1_low_Tower_0.geometry}
            material={materials.Tower}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Door2_low_Tower_0.geometry}
            material={materials.Tower}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Roof_low_Tower_0.geometry}
            material={materials.Tower}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Windows_low_Tower_0.geometry}
            material={materials.Tower}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(lookoutTower)
