/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Gunnar Correa (https://sketchfab.com/gunnarcorrea)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medieval-386f4f0fab8f40bbb3e88dc74e078a40
Title: Medieval
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import quary from '../assets/quary.glb'

/**
 * React component for rendering a 3D model of a quarry.
 * @param {object} props - Props passed to the component.
 * @returns {JSX.Element} JSX representation of the quarry.
 */
function Quarry(props) {
  const { nodes, materials } = useGLTF(quary)
  return (
    <group {...props} dispose={null} position={[0,0.2,0]}>
      <group scale={0.005}>
        <group position={[-246.154, 40.984, -223]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Stairs_StoneBrick_0.geometry}
            material={materials.StoneBrick}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Stairs_Wood_0.geometry}
            material={materials.Wood}
          />
        </group>
        <group position={[-13.235, 619.046, -50.588]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Roof_Wood_0.geometry}
            material={materials.Wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Roof_Wood_fine_0.geometry}
            material={materials.Wood_fine}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Roof_Roof_0.geometry}
            material={materials.Roof}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floors_Wood_0.geometry}
          material={materials.Wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floors_Wood_fine_0.geometry}
          material={materials.Wood_fine}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Base_wood_Wood_0.geometry}
          material={materials.Wood}
          position={[-152.869, 339.417, -0.038]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stair_bases_Wood_0.geometry}
          material={materials.Wood}
          position={[152.374, 50.291, -228.28]}
          scale={[0.033, 0.02, 0.052]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['1Floor_StoneBrick_0'].geometry}
          material={materials.StoneBrick}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['1Floor_Wood_0'].geometry}
          material={materials.Wood}
        />
      </group>
    </group>
  )
}

useGLTF.preload(quary)

export default Quarry;