/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-stables-f9e7871e6b2f42af81375d05dd786c14
Title: Low Poly Stables
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import stables from '../assets/stables.glb'

export default function Stables(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(stables)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="5177df16f8cb4870ad38987f54454f78fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Body" position={[387.088, 148.096, 48.879]} scale={[0.692, 1.591, 1]}>
                  <mesh
                    name="Body_03_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Body_03_-_Default_0'].geometry}
                    material={materials['03_-_Default']}
                  />
                  <group
                    name="Tail"
                    position={[-0.992, -10.669, -49.442]}
                    rotation={[0, -1.571, 0]}
                    scale={[1, 0.629, 1.444]}>
                    <mesh
                      name="Tail_08_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Tail_08_-_Default_0'].geometry}
                      material={materials['08_-_Default']}
                    />
                  </group>
                  <group
                    name="Head"
                    position={[0, 34.599, 188.933]}
                    rotation={[-1.058, 0, 0]}
                    scale={[1.444, 1, 0.742]}>
                    <mesh
                      name="Head_03_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Head_03_-_Default_0'].geometry}
                      material={materials['03_-_Default']}
                    />
                    <mesh
                      name="Head_07_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Head_07_-_Default_0'].geometry}
                      material={materials['07_-_Default']}
                    />
                    <mesh
                      name="Head_08_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Head_08_-_Default_0'].geometry}
                      material={materials['08_-_Default']}
                    />
                  </group>
                  <group
                    name="Left_arm"
                    position={[36.088, -10.73, 127.022]}
                    scale={[0.914, 0.398, 0.633]}>
                    <group name="Object_13" position={[-49.374, 0, 0]}>
                      <mesh
                        name="Left_arm_03_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Left_arm_03_-_Default_0'].geometry}
                        material={materials['03_-_Default']}
                      />
                    </group>
                    <group
                      name="Joint"
                      position={[0.758, -68.432, 8.044]}
                      rotation={[1.484, 0, 0]}
                      scale={[1.58, 1.581, 1.581]}>
                      <mesh
                        name="Joint_03_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Joint_03_-_Default_0'].geometry}
                        material={materials['03_-_Default']}
                      />
                      <group
                        name="Left_knee"
                        position={[-0.48, 3.454, 17.224]}
                        rotation={[-1.658, 0, 0]}
                        scale={0.513}>
                        <group name="Object_18" position={[-49.374, 0, 0]}>
                          <mesh
                            name="Left_knee_03_-_Default_0"
                            castShadow
                            receiveShadow
                            geometry={nodes['Left_knee_03_-_Default_0'].geometry}
                            material={materials['03_-_Default']}
                          />
                        </group>
                        <group
                          name="Left_hoof"
                          position={[-0.604, -92.017, -9.307]}
                          rotation={[1.658, 0, 0]}
                          scale={1.947}>
                          <mesh
                            name="Left_hoof_03_-_Default_0"
                            castShadow
                            receiveShadow
                            geometry={nodes['Left_hoof_03_-_Default_0'].geometry}
                            material={materials['03_-_Default']}
                          />
                          <mesh
                            name="Left_hoof_07_-_Default_0"
                            castShadow
                            receiveShadow
                            geometry={nodes['Left_hoof_07_-_Default_0'].geometry}
                            material={materials['07_-_Default']}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                  <group
                    name="Left_leg"
                    position={[36.088, -20.414, -6.768]}
                    scale={[0.914, 0.398, 0.633]}>
                    <group name="Object_24" position={[-49.374, 0, 0]}>
                      <mesh
                        name="Left_leg_03_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Left_leg_03_-_Default_0'].geometry}
                        material={materials['03_-_Default']}
                      />
                    </group>
                    <group
                      name="Joint_1"
                      position={[0.758, -56.229, 2.225]}
                      rotation={[1.458, 0, 0]}
                      scale={[1.58, 1.581, 1.221]}>
                      <mesh
                        name="Joint_03_-_Default_0_1"
                        castShadow
                        receiveShadow
                        geometry={nodes['Joint_03_-_Default_0_1'].geometry}
                        material={materials['03_-_Default']}
                      />
                      <group
                        name="Left_knee_1"
                        position={[-0.48, 1.828, 12.081]}
                        rotation={[-1.707, 0, 0]}
                        scale={[0.513, 0.665, 0.513]}>
                        <group name="Object_29" position={[-49.374, 0, 0]}>
                          <mesh
                            name="Left_knee_03_-_Default_0_1"
                            castShadow
                            receiveShadow
                            geometry={nodes['Left_knee_03_-_Default_0_1'].geometry}
                            material={materials['03_-_Default']}
                          />
                        </group>
                        <group
                          name="Left_hoof_1"
                          position={[-0.604, -92.017, -9.307]}
                          rotation={[1.658, 0, 0]}
                          scale={1.947}>
                          <mesh
                            name="Left_hoof_03_-_Default_0_1"
                            castShadow
                            receiveShadow
                            geometry={nodes['Left_hoof_03_-_Default_0_1'].geometry}
                            material={materials['03_-_Default']}
                          />
                          <mesh
                            name="Left_hoof_07_-_Default_0_1"
                            castShadow
                            receiveShadow
                            geometry={nodes['Left_hoof_07_-_Default_0_1'].geometry}
                            material={materials['07_-_Default']}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                  <group
                    name="Right_leg"
                    position={[-35.216, -20.414, -6.768]}
                    scale={[0.914, 0.398, 0.633]}>
                    <mesh
                      name="Right_leg_03_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Right_leg_03_-_Default_0'].geometry}
                      material={materials['03_-_Default']}
                    />
                    <group
                      name="Joint_2"
                      position={[0, -56.229, 2.225]}
                      rotation={[1.458, 0, 0]}
                      scale={[1.58, 1.581, 1.221]}>
                      <mesh
                        name="Joint_03_-_Default_0_2"
                        castShadow
                        receiveShadow
                        geometry={nodes['Joint_03_-_Default_0_2'].geometry}
                        material={materials['03_-_Default']}
                      />
                      <group
                        name="Right_knee"
                        position={[0.31, 1.828, 12.081]}
                        rotation={[-1.707, 0, 0]}
                        scale={[0.513, 0.665, 0.513]}>
                        <group name="Object_39" position={[-49.374, 0, 0]}>
                          <mesh
                            name="Right_knee_03_-_Default_0"
                            castShadow
                            receiveShadow
                            geometry={nodes['Right_knee_03_-_Default_0'].geometry}
                            material={materials['03_-_Default']}
                          />
                        </group>
                      </group>
                      <group
                        name="Right_hoof"
                        position={[0, -0.032, 73.475]}
                        rotation={[-0.026, 0, 0]}
                        scale={[1, 1, 1.295]}>
                        <mesh
                          name="Right_hoof_03_-_Default_0"
                          castShadow
                          receiveShadow
                          geometry={nodes['Right_hoof_03_-_Default_0'].geometry}
                          material={materials['03_-_Default']}
                        />
                        <mesh
                          name="Right_hoof_07_-_Default_0"
                          castShadow
                          receiveShadow
                          geometry={nodes['Right_hoof_07_-_Default_0'].geometry}
                          material={materials['07_-_Default']}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="Right_arm"
                    position={[-35.216, -10.73, 127.022]}
                    scale={[0.914, 0.398, 0.633]}>
                    <mesh
                      name="Right_arm_03_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Right_arm_03_-_Default_0'].geometry}
                      material={materials['03_-_Default']}
                    />
                    <group
                      name="Joint_3"
                      position={[0, -68.432, 8.044]}
                      rotation={[1.484, 0, 0]}
                      scale={[1.58, 1.581, 1.581]}>
                      <mesh
                        name="Joint_03_-_Default_0_3"
                        castShadow
                        receiveShadow
                        geometry={nodes['Joint_03_-_Default_0_3'].geometry}
                        material={materials['03_-_Default']}
                      />
                      <group
                        name="Right_knee_1"
                        position={[0.31, 3.454, 17.224]}
                        rotation={[-1.658, 0, 0]}
                        scale={0.513}>
                        <group name="Object_49" position={[-49.374, 0, 0]}>
                          <mesh
                            name="Right_knee_03_-_Default_0_1"
                            castShadow
                            receiveShadow
                            geometry={nodes['Right_knee_03_-_Default_0_1'].geometry}
                            material={materials['03_-_Default']}
                          />
                        </group>
                        <group
                          name="Right_hoof_1"
                          position={[-0.604, -92.017, -9.307]}
                          rotation={[1.658, 0, 0]}
                          scale={1.947}>
                          <mesh
                            name="Right_hoof_03_-_Default_0_1"
                            castShadow
                            receiveShadow
                            geometry={nodes['Right_hoof_03_-_Default_0_1'].geometry}
                            material={materials['03_-_Default']}
                          />
                          <mesh
                            name="Right_hoof_07_-_Default_0_1"
                            castShadow
                            receiveShadow
                            geometry={nodes['Right_hoof_07_-_Default_0_1'].geometry}
                            material={materials['07_-_Default']}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group
                  name="Stable"
                  position={[497.818, -12.298, 0.58]}
                  rotation={[0, -1.571, 0]}
                  scale={[1, 1, 0.66]}>
                  <mesh
                    name="Stable_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Stable_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                  <mesh
                    name="Stable_02_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Stable_02_-_Default_0'].geometry}
                    material={materials['02_-_Default']}
                  />
                  <mesh
                    name="Stable_09_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Stable_09_-_Default_0'].geometry}
                    material={materials['09_-_Default']}
                  />
                </group>
                <group
                  name="Body002"
                  position={[-5.039, 148.096, 48.879]}
                  scale={[0.692, 1.591, 1]}>
                  <mesh
                    name="Body002_03_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Body002_03_-_Default_0'].geometry}
                    material={materials['03_-_Default']}
                  />
                  <group
                    name="Head002"
                    position={[0, 34.599, 188.933]}
                    rotation={[-1.058, 0, 0]}
                    scale={[1.444, 1, 0.742]}>
                    <mesh
                      name="Head002_03_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Head002_03_-_Default_0'].geometry}
                      material={materials['03_-_Default']}
                    />
                    <mesh
                      name="Head002_07_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Head002_07_-_Default_0'].geometry}
                      material={materials['07_-_Default']}
                    />
                    <mesh
                      name="Head002_08_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Head002_08_-_Default_0'].geometry}
                      material={materials['08_-_Default']}
                    />
                  </group>
                  <group
                    name="Left_arm002"
                    position={[36.088, -10.73, 127.022]}
                    scale={[0.914, 0.398, 0.633]}>
                    <group name="Object_65" position={[-49.374, 0, 0]}>
                      <mesh
                        name="Left_arm002_03_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Left_arm002_03_-_Default_0'].geometry}
                        material={materials['03_-_Default']}
                      />
                    </group>
                    <group
                      name="Joint007"
                      position={[0.758, -68.432, 8.044]}
                      rotation={[1.484, 0, 0]}
                      scale={[1.58, 1.581, 1.581]}>
                      <mesh
                        name="Joint007_03_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Joint007_03_-_Default_0'].geometry}
                        material={materials['03_-_Default']}
                      />
                      <group
                        name="Left_knee003"
                        position={[-0.48, 3.454, 17.224]}
                        rotation={[-1.658, 0, 0]}
                        scale={0.513}>
                        <group name="Object_70" position={[-49.374, 0, 0]}>
                          <mesh
                            name="Left_knee003_03_-_Default_0"
                            castShadow
                            receiveShadow
                            geometry={nodes['Left_knee003_03_-_Default_0'].geometry}
                            material={materials['03_-_Default']}
                          />
                        </group>
                        <group
                          name="Left_hoof003"
                          position={[-0.604, -92.017, -9.307]}
                          rotation={[1.658, 0, 0]}
                          scale={1.947}>
                          <mesh
                            name="Left_hoof003_03_-_Default_0"
                            castShadow
                            receiveShadow
                            geometry={nodes['Left_hoof003_03_-_Default_0'].geometry}
                            material={materials['03_-_Default']}
                          />
                          <mesh
                            name="Left_hoof003_07_-_Default_0"
                            castShadow
                            receiveShadow
                            geometry={nodes['Left_hoof003_07_-_Default_0'].geometry}
                            material={materials['07_-_Default']}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                  <group
                    name="Left_leg002"
                    position={[36.088, -20.414, -6.768]}
                    scale={[0.914, 0.398, 0.633]}>
                    <group name="Object_76" position={[-49.374, 0, 0]}>
                      <mesh
                        name="Left_leg002_03_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Left_leg002_03_-_Default_0'].geometry}
                        material={materials['03_-_Default']}
                      />
                    </group>
                    <group
                      name="Joint008"
                      position={[0.758, -56.229, 2.225]}
                      rotation={[1.458, 0, 0]}
                      scale={[1.58, 1.581, 1.221]}>
                      <mesh
                        name="Joint008_03_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Joint008_03_-_Default_0'].geometry}
                        material={materials['03_-_Default']}
                      />
                      <group
                        name="Left_knee004"
                        position={[-0.48, 1.828, 12.081]}
                        rotation={[-1.707, 0, 0]}
                        scale={[0.513, 0.665, 0.513]}>
                        <group name="Object_81" position={[-49.374, 0, 0]}>
                          <mesh
                            name="Left_knee004_03_-_Default_0"
                            castShadow
                            receiveShadow
                            geometry={nodes['Left_knee004_03_-_Default_0'].geometry}
                            material={materials['03_-_Default']}
                          />
                        </group>
                        <group
                          name="Left_hoof004"
                          position={[-0.604, -92.017, -9.307]}
                          rotation={[1.658, 0, 0]}
                          scale={1.947}>
                          <mesh
                            name="Left_hoof004_03_-_Default_0"
                            castShadow
                            receiveShadow
                            geometry={nodes['Left_hoof004_03_-_Default_0'].geometry}
                            material={materials['03_-_Default']}
                          />
                          <mesh
                            name="Left_hoof004_07_-_Default_0"
                            castShadow
                            receiveShadow
                            geometry={nodes['Left_hoof004_07_-_Default_0'].geometry}
                            material={materials['07_-_Default']}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                  <group
                    name="Right_arm002"
                    position={[-35.216, -10.73, 127.022]}
                    scale={[0.914, 0.398, 0.633]}>
                    <mesh
                      name="Right_arm002_03_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Right_arm002_03_-_Default_0'].geometry}
                      material={materials['03_-_Default']}
                    />
                    <group
                      name="Joint005"
                      position={[0, -68.432, 8.044]}
                      rotation={[1.484, 0, 0]}
                      scale={[1.58, 1.581, 1.581]}>
                      <mesh
                        name="Joint005_03_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Joint005_03_-_Default_0'].geometry}
                        material={materials['03_-_Default']}
                      />
                      <group
                        name="Right_knee004"
                        position={[0.31, 3.454, 17.224]}
                        rotation={[-1.658, 0, 0]}
                        scale={0.513}>
                        <group name="Object_91" position={[-49.374, 0, 0]}>
                          <mesh
                            name="Right_knee004_03_-_Default_0"
                            castShadow
                            receiveShadow
                            geometry={nodes['Right_knee004_03_-_Default_0'].geometry}
                            material={materials['03_-_Default']}
                          />
                        </group>
                        <group
                          name="Right_hoof004"
                          position={[-0.604, -92.017, -9.307]}
                          rotation={[1.658, 0, 0]}
                          scale={1.947}>
                          <mesh
                            name="Right_hoof004_03_-_Default_0"
                            castShadow
                            receiveShadow
                            geometry={nodes['Right_hoof004_03_-_Default_0'].geometry}
                            material={materials['03_-_Default']}
                          />
                          <mesh
                            name="Right_hoof004_07_-_Default_0"
                            castShadow
                            receiveShadow
                            geometry={nodes['Right_hoof004_07_-_Default_0'].geometry}
                            material={materials['07_-_Default']}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                  <group
                    name="Right_leg002"
                    position={[-35.216, -20.414, -6.768]}
                    scale={[0.914, 0.398, 0.633]}>
                    <mesh
                      name="Right_leg002_03_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Right_leg002_03_-_Default_0'].geometry}
                      material={materials['03_-_Default']}
                    />
                    <group
                      name="Joint006"
                      position={[0, -56.229, 2.225]}
                      rotation={[1.458, 0, 0]}
                      scale={[1.58, 1.581, 1.221]}>
                      <mesh
                        name="Joint006_03_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Joint006_03_-_Default_0'].geometry}
                        material={materials['03_-_Default']}
                      />
                      <group
                        name="Right_hoof003"
                        position={[0, -0.032, 73.475]}
                        rotation={[-0.026, 0, 0]}
                        scale={[1, 1, 1.295]}>
                        <mesh
                          name="Right_hoof003_03_-_Default_0"
                          castShadow
                          receiveShadow
                          geometry={nodes['Right_hoof003_03_-_Default_0'].geometry}
                          material={materials['03_-_Default']}
                        />
                        <mesh
                          name="Right_hoof003_07_-_Default_0"
                          castShadow
                          receiveShadow
                          geometry={nodes['Right_hoof003_07_-_Default_0'].geometry}
                          material={materials['07_-_Default']}
                        />
                      </group>
                      <group
                        name="Right_knee003"
                        position={[0.31, 1.828, 12.081]}
                        rotation={[-1.707, 0, 0]}
                        scale={[0.513, 0.665, 0.513]}>
                        <group name="Object_104" position={[-49.374, 0, 0]}>
                          <mesh
                            name="Right_knee003_03_-_Default_0"
                            castShadow
                            receiveShadow
                            geometry={nodes['Right_knee003_03_-_Default_0'].geometry}
                            material={materials['03_-_Default']}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                  <group
                    name="Tail002"
                    position={[-0.992, -10.669, -49.442]}
                    rotation={[0, -1.571, 0]}
                    scale={[1, 0.629, 1.444]}>
                    <mesh
                      name="Tail002_08_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Tail002_08_-_Default_0'].geometry}
                      material={materials['08_-_Default']}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(stables)
