/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Avmifi (https://sketchfab.com/Avmifi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stables-low-poly-116065ff36c64fe9b8e8edcf6c382a50
Title: Stables (low poly)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import stables from '../assets/stables.glb'
import Farm from "./Farm.jsx";

function Stables(props) {
  const { nodes, materials } = useGLTF(stables)
  return (
    <group {...props} dispose={null} position={[0,0.3,0]}>
      <group scale={0.3}>
      <group rotation={[-Math.PI / 2, 0, 0]} >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial.geometry}
              material={materials.lambert3}
          />
          <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_1.geometry}
              material={materials.lambert4}
          />
        </group>
      </group>
        </group>
    </group>
  )
}

useGLTF.preload(stables)

export default Stables;