/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Olosta (https://sketchfab.com/Olosta)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medieval-house-4-b42578994a334bb1a544c51043276f85
Title: Medieval House 4
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import steelMine from '../assets/steelMine.glb'

export default function SteelMine(props) {
  const { nodes, materials } = useGLTF(steelMine)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.House4_House4_M_0.geometry}
        material={materials.House4_M}
        scale={0.004}
      />
    </group>
  )
}

useGLTF.preload(steelMine)
