/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Batonian (https://sketchfab.com/Batonian)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/fantasy-army-tent-b53f7ed48de1406b8784b9792f0fb4ac
Title: Fantasy Army Tent
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import trainingYard from '../assets/trainingYard.glb'

export default function TrainingYard(props) {
  const { nodes, materials } = useGLTF(trainingYard)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.material_0}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/trainingYard.glb')
