/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Freepoly.org (https://sketchfab.com/blackrray)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wood-plant-house-freepolyorg-0547e252f3bc4350befbe6ffc2a583b9
Title: Wood Plant House-Freepoly.org
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import woodStockpile from '../assets/woodStockpile.glb'

/**
 * React component for rendering a 3D model of a wood stockpile.
 * @param {object} props - Props passed to the component.
 * @returns {JSX.Element} JSX representation of the wood stockpile.
 */
export default function WoodStockpile(props) {
  const { nodes, materials } = useGLTF(woodStockpile)
  return (
    <group {...props} dispose={null} scale={0.5}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.76}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-212.949, 74.161, 229.367]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['4_4_0'].geometry}
              material={materials.material_2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['4_4_0_1'].geometry}
              material={materials.material_2}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['1_1_0'].geometry}
            material={materials.material}
            position={[30.948, 675.544, 195.447]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['2_2_0'].geometry}
            material={materials.material_1}
            position={[30.948, 703.948, 135.382]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['3_3_0'].geometry}
            material={materials.material_3}
            position={[-514.446, 269.3, 137.181]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(woodStockpile)
