/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Northcliffe (https://sketchfab.com/Samson.Northcliffe.Rydenko)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/warcraft-3-alliance-footmanfanmade-201452e568064aedadccfafb668ef6a5
Title: Warcraft 3 alliance footman(fanmade)
*/

import React, {useEffect, useRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import knight from '../../../assets/knight.glb'

export default function Knight(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(knight)
  const { actions , names} = useAnimations(animations, group)
  useEffect(() =>
  {
    actions[names[0]].play()
  }, [])
  return (
    <group ref={group} {...props} dispose={null} position={[0,6,0]}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          position={[0, -0.011, -0.216]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.732}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Footman_rig_69" position={[0, 0, 0.04]}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Armor_2}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials.Armor_2}
                    skeleton={nodes.Object_9.skeleton}
                  />
                  <skinnedMesh
                    name="Object_11"
                    geometry={nodes.Object_11.geometry}
                    material={materials['Armor_2.001']}
                    skeleton={nodes.Object_11.skeleton}
                  />
                  <skinnedMesh
                    name="Object_13"
                    geometry={nodes.Object_13.geometry}
                    material={materials.Metal}
                    skeleton={nodes.Object_13.skeleton}
                  />
                  <skinnedMesh
                    name="Object_15"
                    geometry={nodes.Object_15.geometry}
                    material={materials['Armor_2.001']}
                    skeleton={nodes.Object_15.skeleton}
                  />
                  <skinnedMesh
                    name="Object_17"
                    geometry={nodes.Object_17.geometry}
                    material={materials['Armor_2.001']}
                    skeleton={nodes.Object_17.skeleton}
                  />
                  <skinnedMesh
                    name="Object_19"
                    geometry={nodes.Object_19.geometry}
                    material={materials.Armor_2}
                    skeleton={nodes.Object_19.skeleton}
                  />
                  <skinnedMesh
                    name="Object_21"
                    geometry={nodes.Object_21.geometry}
                    material={materials.body}
                    skeleton={nodes.Object_21.skeleton}
                  />
                  <skinnedMesh
                    name="Object_23"
                    geometry={nodes.Object_23.geometry}
                    material={materials['body.001']}
                    skeleton={nodes.Object_23.skeleton}
                  />
                  <skinnedMesh
                    name="Object_25"
                    geometry={nodes.Object_25.geometry}
                    material={materials.Metal}
                    skeleton={nodes.Object_25.skeleton}
                  />
                  <skinnedMesh
                    name="Object_27"
                    geometry={nodes.Object_27.geometry}
                    material={materials['Armor_2.001']}
                    skeleton={nodes.Object_27.skeleton}
                  />
                  <skinnedMesh
                    name="Object_29"
                    geometry={nodes.Object_29.geometry}
                    material={materials.Metal}
                    skeleton={nodes.Object_29.skeleton}
                  />
                  <skinnedMesh
                    name="Object_31"
                    geometry={nodes.Object_31.geometry}
                    material={materials['Armor_2.001']}
                    skeleton={nodes.Object_31.skeleton}
                  />
                  <skinnedMesh
                    name="Object_33"
                    geometry={nodes.Object_33.geometry}
                    material={materials.Metal}
                    skeleton={nodes.Object_33.skeleton}
                  />
                  <group name="arm_strap_bottom_55" />
                  <group name="arm_strap_top_56" />
                  <group name="belt_57" />
                  <group name="chest_58" />
                  <group name="cross_59" />
                  <group name="cylt_60" />
                  <group name="cylt_sides_61" />
                  <group name="eyes_Sphere_62" />
                  <group name="head_merged_63" />
                  <group name="helmet_64" />
                  <group name="shield_65" />
                  <group name="shoulder_pads_66" />
                  <group name="tail_67" />
                  <group name="thigh_plate_68" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(knight)
