/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Parelaxel (https://sketchfab.com/parelaxel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/small-stylised-bush-a83fd7049a784ca6bc0095e7323451d0
Title: Small Stylised Bush
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import bush from '../../assets/small_stylised_bush.glb'

function Bush({position}) {
  const { nodes, materials } = useGLTF(bush);
  return (
    <group dispose={null}>
        <group scale={0.02} position={position}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.BushSmall_phong9_0.geometry}
              material={materials.phong9}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.BushSmall_phong10_0.geometry}
              material={materials.phong10}
            />
        </group>
    </group>
  );
}

useGLTF.preload("/small_stylised_bush.glb");

export default Bush;