/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: JoshGarber (https://sketchfab.com/JoshGarber)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/castle-3d-model-23eb94cac33d4099b7185a81bdc038e4
Title: Castle 3D Model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import castle from '../../assets/castle.glb'

/**
 * React component for rendering a 3D model of a Castle.
 * @param {object} props - Props passed to the component.
 * @returns {JSX.Element} JSX representation of the castle.
 */
export default function Castle({props}) {
  const { nodes, materials } = useGLTF(castle)
  return (
    <group {...props} dispose={null} scale={0.11+props}>
      <group position={[53.5, 22.6, 40]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.TexturesCom_BrickMedievalBlocks0145_1_seamless_S_Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.Gothic_Window_Outside_Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.concrete1_Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.Tudor_Window_Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.rough_plaster_brick_04_diff_1k_Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.Counting_House_Door_Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.TexturesCom_RooftilesCeramicOld0090_1_seamless_S_Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.arch1_Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.Arched_Window_Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials.TexturesCom_OrnamentsShields0055_7_S_Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.Metal003_1K_Color_Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials.trim3_Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials.TexturesCom_OrnamentBorder0037_1_seamless_S_Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_17.geometry}
          material={materials.Concrete036_1K_Color_Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials.TexturesCom_ConcreteFence0028_1_seamless_S_Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_19.geometry}
          material={materials.Chapel_Window_Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_20.geometry}
          material={materials.PavingStones046_1K_Color_Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_21.geometry}
          material={materials.trim4_Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_22.geometry}
          material={materials.Wood049_1K_Color_Mat}
        />
      </group>
    </group>
  )
}

useGLTF.preload(castle)
