/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: blrr.studio (https://sketchfab.com/blrr.studio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mossy-cobbles-tilable-material-99d95893e6c94d1eb6b5fb9bd0f79ec9
Title: Mossy cobbles - tilable material.
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import cobblestones from '../../assets/cobblestones.glb'

export default function Cobblestones({position}) {
  const { nodes, materials } = useGLTF(cobblestones)
  return (
    <group dispose={null}>
      <group scale={0.3} position={position}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane004__0.geometry}
            material={materials['Scene_-_Root']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane004__0_1.geometry}
            material={materials['Scene_-_Root']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(cobblestones)
