/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Rei (https://sketchfab.com/Rei-i)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/grass-field-779f6f69c94b4f15b65f28022550af58
Title: grass field
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import ground from '../../assets/ground.glb'

export default function Ground(props) {
  const { nodes, materials } = useGLTF(ground)
  return (
    <group {...props} dispose={null} scale={0.1} position={[0,3,0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['������������_������_1_����������������1_0'].geometry}
        material={materials.material}
        position={[0, -18.974, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['������������_������_����������������1_0'].geometry}
        material={materials.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['������������_������_2_����������������1_0'].geometry}
        material={materials.material}
      />
    </group>
  )
}

useGLTF.preload(ground)
