/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: cattleya (https://sketchfab.com/cattleya)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-wood-fence-on-grass-d35a038f74ea47819459cabae8c28c62
Title: Low Poly wood fence on grass
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import ground from '../../assets/ground.glb'

export default function Ground(props) {
  const { nodes, materials } = useGLTF(ground)
  return (
    <group {...props} dispose={null} scale={2} position={[0,4,0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.cell_grass}
        />
        {/*<mesh
          scale={0.1}
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.fence2}
        />*/}
      </group>
    </group>
  )
}

useGLTF.preload(ground)
