/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Kevin Saleh (https://sketchfab.com/Kevin.Saleh)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/medieval-house-01-mid-poly-67e33f1ba7ea4d90bf9f637e3d2cd74a
Title: Medieval House 01 (Mid Poly)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import houseObject from '../../assets/medieval_house_01_mid_poly.glb'

function House(props) {
  const { nodes, materials } = useGLTF(houseObject);
  return (
    <group {...props} dispose={null}>
      <group scale={0.003}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wood_Wood_0.geometry}
          material={materials.Wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall_Wall_0.geometry}
          material={materials.Wall}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WallBrick_Wall_Brick_0.geometry}
          material={materials.Wall_Brick}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roof_Roof_0.geometry}
          material={materials.Roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DoorAndWindow_Door_And_Window_0.geometry}
          material={materials.Door_And_Window}
        />
      </group>
    </group>
  );
}

useGLTF.preload(houseObject);

export default House;