/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: D.Milekhin (https://sketchfab.com/D.Milekhin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stilized-house-191a15100a9a487fa39540a208bed857
Title: Stilized house
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import stoneStockpile from '../../assets/stoneStockpile.glb'

/**
 * React component for rendering a 3D model of a stone stockpile.
 * @param {object} props - Props passed to the component.
 * @returns {JSX.Element} JSX representation of the stone stockpile.
 */
export default function StoneStockpile(props) {
  const { nodes, materials } = useGLTF(stoneStockpile)
  return (
    <group {...props} dispose={null} position={[1.3,0,0]}>
      <group scale={0.004}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_House__0.geometry}
          material={materials['Scene_-_Root']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload(stoneStockpile)
