/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Moonlightlll (https://sketchfab.com/Moonlightlll)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medieval-tavern-03f758757c3e448d81f50831b8533c98
Title: Medieval Tavern
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import tavern from '../../assets/tavern.glb'

/**
 * React component for rendering a 3D model of a medieval tavern.
 * @param {object} props - Props passed to the component.
 * @returns {JSX.Element} JSX representation of the medieval tavern.
 */
export default function Tavern(props) {
  const { nodes, materials } = useGLTF(tavern)
  return (
    <group {...props} dispose={null} position={[0,-0.5,1]}>
      <group scale={0.015}>
        <group
          position={[0, 54.867, -394.938]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[100, 100, 18.14]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_Old_stone_wall_moss_0.geometry}
            material={materials.Old_stone_wall_moss}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_Ground_Peables_01_0.geometry}
            material={materials.Ground_Peables_01}
          />
        </group>
        <group position={[0, 172.475, -452.846]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_roof_09_0.geometry}
            material={materials.roof_09}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_Material001_0.geometry}
            material={materials['Material.001']}
          />
        </group>
        <group position={[99.972, 221.919, -385.785]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003_Material012_0.geometry}
            material={materials['Material.012']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003_Material015_0.geometry}
            material={materials['Material.015']}
          />
        </group>
        <group
          position={[-15.133, 222.447, -625.292]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[41.688, 30.342, 35.423]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube140_Material013_0.geometry}
            material={materials['Material.013']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube140_Material014_0.geometry}
            material={materials['Material.014']}
          />
        </group>
        <group position={[95.51, 272.301, -309.63]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube199_Material021_0.geometry}
            material={materials['Material.021']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube199_Material021_0_1.geometry}
            material={materials['Material.021']}
          />
        </group>
        <group position={[113.627, 190.318, -448.583]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube261_Material025_0.geometry}
            material={materials['Material.025']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube261_Material025_0_1.geometry}
            material={materials['Material.025']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material_0.geometry}
          material={materials.Material}
          position={[0, 172.53, -452.825]}
          rotation={[-1.576, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_Material005_0.geometry}
          material={materials['Material.005']}
          position={[92.13, 167.905, -385.472]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[39.946, 29.074, 33.942]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube046_Stone_0.geometry}
          material={materials.Stone}
          position={[157.813, 69.194, -299.346]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube139_Material003_0.geometry}
          material={materials['Material.003']}
          position={[-14.819, 167.905, -620.641]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[39.946, 29.074, 33.942]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube141_Material019_0.geometry}
          material={materials['Material.019']}
          position={[57.9, 254.159, -577.467]}
          rotation={[-Math.PI / 2, 0.049, 0]}
          scale={[36.409, 14.133, 17.73]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube164_Material002_0.geometry}
          material={materials['Material.002']}
          position={[115.489, 206.651, -530.002]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube194_Stone_0.geometry}
          material={materials.Stone}
          position={[79.136, 69.194, -323.692]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={88.176}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube157_Material020_0.geometry}
          material={materials['Material.020']}
          position={[57.9, 254.159, -264.087]}
          rotation={[-Math.PI / 2, 0.049, 0]}
          scale={[36.409, 14.133, 17.73]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube200_Material011_0.geometry}
          material={materials['Material.011']}
          position={[-6.302, 101.247, -483.746]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube251_Material010_0.geometry}
          material={materials['Material.010']}
          position={[67.474, 235.702, -628.311]}
          rotation={[-Math.PI / 2, 1.066, Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube257_Material008_0.geometry}
          material={materials['Material.008']}
          position={[127.791, 196.223, -401.334]}
          rotation={[0, 0.279, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube303_Material004_0.geometry}
          material={materials['Material.004']}
          position={[13.348, 137.221, -630.777]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.944, 14.347, 3.528]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube367_Material027_0.geometry}
          material={materials['Material.027']}
          position={[-14.506, 210.563, -657.766]}
          rotation={[-Math.PI / 2, 0, 1.581]}
          scale={[-1.944, 17.58, 3.528]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube368_Material006_0.geometry}
          material={materials['Material.006']}
          position={[133.71, 213.65, -385.015]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube391_Material024_0.geometry}
          material={materials['Material.024']}
          position={[91.784, 244.504, -309.924]}
          rotation={[-Math.PI / 2, 0.053, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube409_Material026_0.geometry}
          material={materials['Material.026']}
          position={[34.545, 226.945, -626.701]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[-0.498, 7.489, 0.952]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube416_Material030_0.geometry}
          material={materials['Material.030']}
          position={[99.184, 131.117, -379.431]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[33.002, 1.826, 1.009]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube420_Material031_0.geometry}
          material={materials['Material.031']}
          position={[12.059, 133.453, -619.836]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[33.002, 1.826, 1.009]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube426_Material009_0.geometry}
          material={materials['Material.009']}
          position={[-67.012, 222.501, -294.415]}
          rotation={[0, Math.PI / 2, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube439_Material016_0.geometry}
          material={materials['Material.016']}
          position={[73.67, 101.674, -421.331]}
          scale={[-1.944, 19.182, 3.528]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube470_Material032_0.geometry}
          material={materials['Material.032']}
          position={[72.89, 116.175, -336.388]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube473_Material038_0.geometry}
          material={materials['Material.038']}
          position={[71.642, 98.884, -447.733]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.738, 16.102, 26.347]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube484_Material017_0.geometry}
          material={materials['Material.017']}
          position={[112.563, 100.5, -299.226]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube526_Material018_0.geometry}
          material={materials['Material.018']}
          position={[-76.675, 125.404, -625.449]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube529_Material035_0.geometry}
          material={materials['Material.035']}
          position={[147.961, 90.653, -299.226]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube535_Material036_0.geometry}
          material={materials['Material.036']}
          position={[178.115, 134.416, -331.026]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[128.145, 103.501, 118.336]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube602_Material037_0.geometry}
          material={materials['Material.037']}
          position={[147.788, 126.711, -299.522]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube605_Material029_0.geometry}
          material={materials['Material.029']}
          position={[-31.86, 222.383, -644.557]}
          rotation={[-Math.PI / 2, 0.651, Math.PI / 2]}
          scale={[16.409, 1.633, 16.409]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube606_Material043_0.geometry}
          material={materials['Material.043']}
          position={[149.936, 89.192, -389.359]}
          rotation={[-Math.PI / 2, 0, -2.704]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube607_Material045_0.geometry}
          material={materials['Material.045']}
          position={[167.417, 80.242, -379.129]}
          rotation={[-Math.PI / 2, 0, -2.705]}
          scale={[1.74, 1.74, 8.423]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube609_Material044_0.geometry}
          material={materials['Material.044']}
          position={[143.901, 80.242, -311.415]}
          rotation={[-Math.PI / 2, 0, 2.356]}
          scale={[1.74, 1.74, 8.423]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube630_Material046_0.geometry}
          material={materials['Material.046']}
          position={[165.603, 82.06, -400.468]}
          rotation={[-Math.PI / 2, 0, 2.397]}
          scale={[5.246, 4.989, 0.668]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube633_Material047_0.geometry}
          material={materials['Material.047']}
          position={[165.981, 80.845, -395.296]}
          rotation={[-Math.PI / 2, 0, 2.397]}
          scale={0.958}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle019_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[160.1, 82.959, -400.687]}
          rotation={[-Math.PI / 2, 0, 2.397]}
          scale={0.364}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle020_Material041_0.geometry}
          material={materials['Material.041']}
          position={[157.912, 91.785, -395.194]}
          rotation={[-Math.PI / 2, 0, -0.984]}
          scale={1.443}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle021__0.geometry}
          material={materials['Circle.021__0']}
          position={[155.788, 89.922, -396.089]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.443}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube636_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[159.51, 90.741, -396.31]}
          rotation={[-Math.PI / 2, 0, -0.984]}
          scale={1.443}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle031__0.geometry}
          material={materials['Circle.021__0']}
          position={[138.439, 91.471, -395.239]}
          rotation={[0.398, -0.701, -2.82]}
          scale={[0.118, 0.118, 0.079]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle032_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[152.697, 89.992, -381.91]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.546}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube604_Stone_Wall_Flag_Floor_0.geometry}
          material={materials.Stone_Wall_Flag_Floor}
          position={[-30.299, 266.434, -362.291]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_Stone_Wall_Flag_Floor_0.geometry}
          material={materials.Stone_Wall_Flag_Floor}
          position={[-30.892, 271.932, -361.913]}
          rotation={[-Math.PI / 2, -0.618, 0]}
          scale={19.299}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle058_Material039_0.geometry}
          material={materials['Material.039']}
          position={[-78.774, 78.783, -642.86]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={8.641}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle059__0.geometry}
          material={materials['Circle.021__0']}
          position={[-77.524, 54.588, -643.563]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={8.641}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle060_Material040_0.geometry}
          material={materials['Material.040']}
          position={[-78.774, 77.841, -642.808]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={8.641}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle061_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[-78.774, 59.246, -642.916]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={11.19}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube644_Material033_0.geometry}
          material={materials['Material.033']}
          position={[128.257, 128.595, -417.557]}
          rotation={[-Math.PI / 2, 0.197, Math.PI / 2]}
          scale={54.08}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_Material023_0.geometry}
          material={materials['Material.023']}
          position={[129.139, 128.441, -450.311]}
          rotation={[-Math.PI / 2, 0.262, 0]}
          scale={[11.984, 31.324, 31.324]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube645_Material028_0.geometry}
          material={materials['Material.028']}
          position={[132.724, 219.963, -386.432]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.201, 27.562, 27.562]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube647_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[74.804, 96.67, -435.907]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={2.108}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_Material022_0.geometry}
          material={materials['Material.022']}
          position={[113.423, 180.792, -577.126]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube160_Material007_0.geometry}
          material={materials['Material.007']}
          position={[-14.776, 181.387, -653.928]}
          rotation={[Math.PI, 1.292, -Math.PI]}
          scale={[-1.95, 19.021, 3.093]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane040_Material022_0.geometry}
          material={materials['Material.022']}
          position={[113.423, 180.792, -501.391]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_Material022_0.geometry}
          material={materials['Material.022']}
          position={[113.423, 180.792, -448.52]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_Material022_0.geometry}
          material={materials['Material.022']}
          position={[113.423, 180.792, -329.504]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_Material022_0.geometry}
          material={materials['Material.022']}
          position={[129.077, 180.792, -385.452]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane037_Material022_0.geometry}
          material={materials['Material.022']}
          position={[72.871, 106.614, -391.038]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_Material022_0.geometry}
          material={materials['Material.022']}
          position={[72.871, 107.346, -527.832]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009_Material022_0.geometry}
          material={materials['Material.022']}
          position={[82.992, 181.187, -626.55]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010_Material022_0.geometry}
          material={materials['Material.022']}
          position={[39.582, 181.187, -626.55]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011_Material022_0.geometry}
          material={materials['Material.022']}
          position={[34.46, 243.757, -626.55]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_Material022_0.geometry}
          material={materials['Material.022']}
          position={[-14.81, 180.834, -652.124]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_Material022_0.geometry}
          material={materials['Material.022']}
          position={[-70.151, 181.211, -626.648]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013_Material022_0.geometry}
          material={materials['Material.022']}
          position={[-97.409, 181.129, -591.525]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019_Material022_0.geometry}
          material={materials['Material.022']}
          position={[-97.409, 181.129, -541.212]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane020_Material022_0.geometry}
          material={materials['Material.022']}
          position={[-97.409, 181.129, -482.855]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane021_Material022_0.geometry}
          material={materials['Material.022']}
          position={[-97.409, 181.129, -434.256]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane022_Material022_0.geometry}
          material={materials['Material.022']}
          position={[-97.409, 181.129, -380.146]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane023_Material022_0.geometry}
          material={materials['Material.022']}
          position={[-97.409, 181.129, -331.769]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane024_Material022_0.geometry}
          material={materials['Material.022']}
          position={[-84.862, 106.894, -565.507]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane025_Material022_0.geometry}
          material={materials['Material.022']}
          position={[-84.862, 106.894, -512.265]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane026_Material022_0.geometry}
          material={materials['Material.022']}
          position={[-84.862, 106.894, -448.157]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane027_Material022_0.geometry}
          material={materials['Material.022']}
          position={[-84.862, 106.894, -382.215]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane028_Material022_0.geometry}
          material={materials['Material.022']}
          position={[-84.862, 106.894, -328.803]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane029_Material022_0.geometry}
          material={materials['Material.022']}
          position={[-66.157, 180.755, -295.315]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane033_Material022_0.geometry}
          material={materials['Material.022']}
          position={[-16.131, 180.755, -295.315]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane034_Material022_0.geometry}
          material={materials['Material.022']}
          position={[31.394, 180.755, -295.315]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane035_Material022_0.geometry}
          material={materials['Material.022']}
          position={[80.903, 180.755, -295.315]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane036_Material022_0.geometry}
          material={materials['Material.022']}
          position={[36.866, 107.026, -590.334]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_Material022_0.geometry}
          material={materials['Material.022']}
          position={[-13.001, 107.026, -590.334]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016_Material022_0.geometry}
          material={materials['Material.022']}
          position={[-60.245, 107.026, -590.334]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_Material022_0.geometry}
          material={materials['Material.022']}
          position={[-60.301, 107.076, -300.544]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane030_Material022_0.geometry}
          material={materials['Material.022']}
          position={[-4.009, 106.839, -300.544]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane031_Material022_0.geometry}
          material={materials['Material.022']}
          position={[49.154, 106.839, -300.544]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane032_Material022_0.geometry}
          material={materials['Material.022']}
          position={[92.011, 252.03, -577.546]}
          rotation={[Math.PI / 2, 1.519, Math.PI]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane038_Material022_0.geometry}
          material={materials['Material.022']}
          position={[92.011, 252.03, -506.708]}
          rotation={[Math.PI / 2, 1.519, Math.PI]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane039_Material022_0.geometry}
          material={materials['Material.022']}
          position={[92.011, 252.03, -431.099]}
          rotation={[Math.PI / 2, 1.519, Math.PI]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane041_Material022_0.geometry}
          material={materials['Material.022']}
          position={[92.011, 252.03, -355.813]}
          rotation={[Math.PI / 2, 1.519, Math.PI]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane042_Material022_0.geometry}
          material={materials['Material.022']}
          position={[92.011, 252.03, -309.865]}
          rotation={[Math.PI / 2, 1.519, Math.PI]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane043_Material022_0.geometry}
          material={materials['Material.022']}
          position={[12.35, 181.187, -638.38]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={[17.12, 8.865, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018_Material022_0.geometry}
          material={materials['Material.022']}
          position={[72.871, 106.614, -336.374]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={[17.403, 12.351, 12.351]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane044_Material034_0.geometry}
          material={materials['Material.034']}
          position={[117.015, 112.266, -417.44]}
          rotation={[-Math.PI / 2, -1.484, Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle062_Material039_0.geometry}
          material={materials['Material.039']}
          position={[-62.933, 64.033, -639.447]}
          rotation={[-Math.PI, Math.PI / 3, Math.PI / 2]}
          scale={8.641}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle063_Material040_0.geometry}
          material={materials['Material.040']}
          position={[-62.091, 64.033, -639.872]}
          rotation={[0, -Math.PI / 3, 1.571]}
          scale={8.641}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle064_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[-46.041, 64.033, -649.264]}
          rotation={[-Math.PI, Math.PI / 3, Math.PI / 2]}
          scale={11.19}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle065_Material040_0.geometry}
          material={materials['Material.040']}
          position={[-41.193, 64.062, -652.002]}
          rotation={[0, -Math.PI / 3, 1.571]}
          scale={8.641}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle066_Material039_0.geometry}
          material={materials['Material.039']}
          position={[-76.888, 98.559, -604.63]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={8.641}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle067_Material040_0.geometry}
          material={materials['Material.040']}
          position={[-76.888, 97.617, -604.578]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={8.641}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle068_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[-76.888, 79.022, -604.686]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={11.19}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle069_Material040_0.geometry}
          material={materials['Material.040']}
          position={[-76.859, 73.454, -604.634]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={8.641}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle048_Material039_0.geometry}
          material={materials['Material.039']}
          position={[-76.888, 124.273, -604.63]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={8.641}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle049_Material040_0.geometry}
          material={materials['Material.040']}
          position={[-76.888, 123.331, -604.578]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={8.641}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle050_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[-76.888, 104.735, -604.686]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={11.19}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle051_Material040_0.geometry}
          material={materials['Material.040']}
          position={[-76.859, 99.168, -604.634]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={8.641}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle052_Material039_0.geometry}
          material={materials['Material.039']}
          position={[101.474, 101.541, -323.939]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          scale={8.641}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle053_Material040_0.geometry}
          material={materials['Material.040']}
          position={[100.532, 101.541, -323.887]}
          rotation={[-Math.PI / 2, 1.571, 0]}
          scale={8.641}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle054_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[81.937, 101.541, -323.995]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          scale={11.19}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle055_Material040_0.geometry}
          material={materials['Material.040']}
          position={[76.37, 101.513, -323.943]}
          rotation={[-Math.PI / 2, 1.571, 0]}
          scale={8.641}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005_Material039_0.geometry}
          material={materials['Material.039']}
          position={[101.474, 82.929, -336.048]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          scale={8.641}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle006_Material040_0.geometry}
          material={materials['Material.040']}
          position={[100.532, 82.929, -335.996]}
          rotation={[-Math.PI / 2, 1.571, 0]}
          scale={8.641}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle007_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[81.937, 82.929, -336.104]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          scale={11.19}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_Material040_0.geometry}
          material={materials['Material.040']}
          position={[76.37, 82.9, -336.052]}
          rotation={[-Math.PI / 2, 1.571, 0]}
          scale={8.641}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Material039_0.geometry}
          material={materials['Material.039']}
          position={[101.474, 82.929, -311.132]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          scale={8.641}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle002_Material040_0.geometry}
          material={materials['Material.040']}
          position={[100.532, 82.929, -311.08]}
          rotation={[-Math.PI / 2, 1.571, 0]}
          scale={8.641}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[81.937, 82.929, -311.188]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          scale={11.19}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004_Material040_0.geometry}
          material={materials['Material.040']}
          position={[76.37, 82.9, -311.135]}
          rotation={[-Math.PI / 2, 1.571, 0]}
          scale={8.641}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle009_Material042_0.geometry}
          material={materials['Material.042']}
          position={[157.861, 90.065, -395.194]}
          rotation={[-1.565, 0.004, 1.078]}
          scale={1.443}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle010_Material041_0.geometry}
          material={materials['Material.041']}
          position={[138.843, 91.677, -394.368]}
          rotation={[0, 0.687, 2.055]}
          scale={1.443}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube142_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[136.864, 90.732, -394.093]}
          rotation={[0, 0.687, 2.055]}
          scale={1.443}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle011_Material042_0.geometry}
          material={materials['Material.042']}
          position={[137.792, 91.672, -395.73]}
          rotation={[-0.008, 0.684, -2.162]}
          scale={1.443}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle012_Material041_0.geometry}
          material={materials['Material.041']}
          position={[157.038, 91.814, -342.843]}
          rotation={[-Math.PI / 2, 0, -1.541]}
          scale={1.443}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube143_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[158.984, 90.77, -342.945]}
          rotation={[-Math.PI / 2, 0, -1.541]}
          scale={1.443}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle013_Material042_0.geometry}
          material={materials['Material.042']}
          position={[157.016, 90.178, -342.818]}
          rotation={[-1.565, 0.004, 1.078]}
          scale={1.443}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle014_Material041_0.geometry}
          material={materials['Material.041']}
          position={[144.543, 91.814, -341.634]}
          rotation={[-Math.PI / 2, 0, 1.403]}
          scale={1.443}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube144_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[142.614, 90.77, -341.915]}
          rotation={[-Math.PI / 2, 0, 1.403]}
          scale={1.443}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle022_Material042_0.geometry}
          material={materials['Material.042']}
          position={[144.569, 90.178, -341.654]}
          rotation={[-1.577, -0.003, -2.261]}
          scale={1.443}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle023_Material041_0.geometry}
          material={materials['Material.041']}
          position={[137.345, 91.814, -319.7]}
          rotation={[-Math.PI / 2, 0, 2.682]}
          scale={1.443}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube145_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[136.519, 90.77, -317.934]}
          rotation={[-Math.PI / 2, 0, 2.682]}
          scale={1.443}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle024_Material042_0.geometry}
          material={materials['Material.042']}
          position={[137.333, 90.178, -319.73]}
          rotation={[-1.57, -0.007, -0.983]}
          scale={1.443}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube146_Material043_0.geometry}
          material={materials['Material.043']}
          position={[147.376, 89.192, -331.201]}
          rotation={[-Math.PI / 2, 0, 2.359]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle025_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[169.279, 82.959, -355.628]}
          rotation={[-Math.PI / 2, 0, 0.533]}
          scale={0.364}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle017_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[152.697, 90.223, -381.91]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.546}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle026_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[152.697, 90.434, -381.91]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.546}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle027_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[152.697, 90.636, -381.91]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.546}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle028_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[152.697, 90.857, -381.91]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.546}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle029_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[152.697, 91.029, -381.91]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.546}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle030_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[152.697, 91.26, -381.91]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.546}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle033_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[152.697, 91.471, -381.91]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.546}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle034_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[152.697, 91.673, -381.91]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.546}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle035_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[152.697, 91.893, -381.91]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.546}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle036_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[141.42, 89.992, -382.231]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.546}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube148_Material046_0.geometry}
          material={materials['Material.046']}
          position={[167.373, 82.429, -350.363]}
          rotation={[-Math.PI / 2, 0, 0.537]}
          scale={[5.246, 4.989, 0.668]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube149_Material047_0.geometry}
          material={materials['Material.047']}
          position={[162.309, 81.213, -351.479]}
          rotation={[-Math.PI / 2, 0, 0.536]}
          scale={0.958}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle037_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[169.156, 83.327, -355.573]}
          rotation={[-Math.PI / 2, 0, 0.536]}
          scale={0.364}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube147_Material046_0.geometry}
          material={materials['Material.046']}
          position={[130.795, 82.429, -310.531]}
          rotation={[-Math.PI / 2, 0, -0.439]}
          scale={[5.246, 4.989, 0.668]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube150_Material047_0.geometry}
          material={materials['Material.047']}
          position={[128.879, 81.213, -315.35]}
          rotation={[-Math.PI / 2, 0, -0.439]}
          scale={0.958}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle038_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[136.109, 83.327, -311.978]}
          rotation={[-Math.PI / 2, 0, -0.439]}
          scale={0.364}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube151_Material046_0.geometry}
          material={materials['Material.046']}
          position={[130.812, 82.429, -349.488]}
          rotation={[-Math.PI / 2, 0, -0.575]}
          scale={[5.246, 4.989, 0.668]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube152_Material047_0.geometry}
          material={materials['Material.047']}
          position={[129.568, 81.213, -354.522]}
          rotation={[-Math.PI / 2, 0, -0.575]}
          scale={0.958}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle018_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[136.273, 83.327, -350.2]}
          rotation={[-Math.PI / 2, 0, -0.575]}
          scale={0.364}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_Stone_0.geometry}
          material={materials.Stone}
          position={[0, 54.867, -394.938]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_Material046_0.geometry}
          material={materials['Material.046']}
          position={[128.84, 82.06, -379.747]}
          rotation={[-Math.PI / 2, 0, 0.246]}
          scale={[5.246, 4.989, 0.668]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_Material047_0.geometry}
          material={materials['Material.047']}
          position={[124.308, 80.845, -382.267]}
          rotation={[-Math.PI / 2, 0, 0.246]}
          scale={0.958}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle016_Old_Metal_0.geometry}
          material={materials.Old_Metal}
          position={[132.041, 82.959, -384.228]}
          rotation={[-Math.PI / 2, 0, 0.246]}
          scale={0.364}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_Stone_brick_wall_0.geometry}
          material={materials.Stone_brick_wall}
          position={[6.177, 53.435, -455.875]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={253.821}
        />
      </group>
    </group>
  )
}

useGLTF.preload(tavern)
