/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: KPMisParrot (https://sketchfab.com/KPMisParrot)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gorilla-tag-pine-tree-assets-5ac1154299bc4ae2a7e34b65b198c399
Title: Gorilla Tag Pine Tree Assets
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import tree from '../../assets/tree.glb'

export default function Tree({position}) {
  const { nodes, materials } = useGLTF(tree)
  return (
    <group dispose={null} position={position}>
      <group scale={0.05}>
        {/*<mesh
          castShadow
          receiveShadow
          geometry={nodes.CorralSignMTPaper_PineTreeSign_0.geometry}
          material={materials.PineTreeSign}
          position={[-6623.292, -681.806, 1545.273]}
          rotation={[0, -0.48, 0]}
        />*/}
        {/*<mesh
          castShadow
          receiveShadow
          geometry={nodes.CorralSignMT_PineTreeSign_0.geometry}
          material={materials.PineTreeSign}
          position={[-6623.292, -681.806, 1545.273]}
          rotation={[0, -0.48, 0]}
        />*/}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Christmastree2023_PineTree_0.geometry}
          material={materials.PineTree}
          position={[-36.322, -200.906, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload(tree)
